Repository BackJinSa/zangBu_Front, pull requests merged in 2025-08, with the labels that each got.

#8 feat: 컴포넌트 설계 및 기본 axios 설계
  src/api/axios.js
  src/api/property/property.js
  src/components/property/AddressSearchMap.vue
  src/components/property/ContactPersonForm.vue
  src/components/property/MoveInDatePicker.vue
  src/components/property/PropertyActionButtons.vue
  src/components/property/PropertyBasicInfoForm.vue
  src/components/property/PropertyDetailForm.vue
  src/pages/property/PropertyRegisterView.vue
  src/stores/property/property.js
Labels: ⭐ feat, 🐯 현빈

#9 feat: 공용 컴포넌트 설계
  src/components/common/Button.vue
  src/components/common/Dropbox.vue
  src/components/common/Header.vue
  src/components/common/Input.vue
  src/components/common/PopupModal.vue
  src/components/common/PropertyCardA.vue
  src/components/common/PropertyCardB.vue
  src/components/common/PropertyCardC.vue
  src/components/common/Search.vue
  src/components/common/Sidebar.vue
Labels: ⭐ feat, 🐯 현빈

#11 feat: /map 페이지 개발
  .env
  TEST_GUIDE.md
  package.json
  src/api/map/map.js
  src/api/map/map.mock.js
  src/pages/map/MapTestView.vue
  src/pages/map/MapView.vue
  src/router/index.js
  src/stores/map/map.js
  test-map.js
Labels: ⭐ feat, 🍾영오

#15 feat: 채팅방 목록 페이지 개발
  src/pages/chat/ChatListView.vue
Labels: ⭐ feat, 🎸수연

#17 feat: input 컴포넌트 개발 및 가이드 페이지 개발
  src/components/common/Input.vue
  src/pages/guide/GuideMainView.vue
  src/pages/guide/InputGuideView.vue
  src/pages/property/PropertyRegisterView.vue
  src/router/index.js
Labels: ⭐ feat, 🐯 현빈

#20 Feat/#1
  package-lock.json
  package.json
  src/api/system/system.js
  src/assets/main.css
  src/components/system/NotificationActionBar.vue
  src/components/system/NotificationBadge.vue
  src/components/system/NotificationCard.vue
  src/components/system/NotificationCardActions.vue
  src/components/system/NotificationCardHeader.vue
  src/components/system/NotificationCardMeta.vue
  src/components/system/NotificationEmpty.vue
  src/components/system/NotificationFilter.vue
  src/components/system/NotificationIcon.vue
  src/components/system/NotificationList.vue
  src/components/system/NotificationPagination.vue
  src/pages/system/NotificationView.vue
  src/stores/system/system.js
Labels: ⭐ feat, ⚽ 경민

#22 feat: 매물 상세보기 기능 구현
  src/pages/map/MapView.vue
Labels: ♻️ refactor, ⭐ feat, 🍾영오

#26 Feat/#1
  package-lock.json
  src/components/notification/NotificationActionBar.vue
  src/components/notification/NotificationBadge.vue
  src/components/notification/NotificationCard.vue
  src/components/notification/NotificationCardActions.vue
  src/components/notification/NotificationCardHeader.vue
  src/components/notification/NotificationCardMeta.vue
  src/components/notification/NotificationEmpty.vue
  src/components/notification/NotificationFilter.vue
  src/components/notification/NotificationIcon.vue
  src/components/notification/NotificationList.vue
  src/components/notification/NotificationPagination.vue
  src/components/system/NotificationActionBar.vue
  src/components/system/NotificationBadge.vue
  src/components/system/NotificationCardActions.vue
  src/components/system/NotificationCardHeader.vue
  src/components/system/NotificationCardMeta.vue
  src/components/system/NotificationEmpty.vue
  src/components/system/NotificationFilter.vue
  src/components/system/NotificationIcon.vue
  src/components/system/NotificationPagination.vue
  src/pages/notification/NotificationView.vue
  src/pages/payment/PaymentView.vue
  src/pages/system/NotificationView.vue
  src/router/index.js
  src/stores/notification/notification.js
  src/stores/payment/payment.js
  src/stores/system/system.js
Labels: ♻️ refactor, ⚽ 경민

#29 feat: PropertyCard 공용 컴포넌트 개발
  src/components/common/PropertyCard.vue
  src/components/common/PropertyCardB.vue
  src/components/common/PropertyCardC.vue
  src/components/common/PropertyCardMain.vue
  src/components/common/PropertyCardWaiting.vue
  src/pages/guide/GuideMainView.vue
  src/pages/guide/PropertyCardGuideView.vue
  src/pages/guide/PropertyCardMainView.vue
  src/pages/guide/PropertyCardWaitingView.vue
  src/router/index.js
Labels: ⭐ feat, 🐱해인

#31 feat: 채팅 페이지 개발
  package.json
  src/assets/main.css
  src/pages/chat/ChatBuyerView.vue
  src/pages/chat/ChatListView.vue
  src/pages/chat/ChatRoomView.vue
  src/pages/chat/ChatSellerView.vue
  src/router/index.js
Labels: ⭐ feat, 🎸수연

#36 feat: 결제 페이지 구현
  package.json
  src/api/payment/payment.js
  src/pages/payment/PaymentConfirmView.vue
  src/pages/payment/PaymentFailView.vue
  src/pages/payment/PaymentSuccessView.vue
  src/pages/payment/PaymentView.vue
  src/router/index.js
Labels: ♻️ refactor, ⭐ feat, 🍾영오

#34 refactor: 채팅방 목록 페이지에 tailwind
  src/pages/chat/ChatListView.vue
  src/pages/chat/ChatRoomView.vue
Labels: ♻️ refactor, 🎸수연

#38 feat: 결제 승인 페이지 구현
  src/pages/payment/PaymentConfirmView.vue
  src/pages/payment/PaymentSuccessView.vue
  src/pages/payment/PaymentView.vue
Labels: 💟 style, ⭐ feat, 🍾영오

#48 refactor: /map 지도 페이지 상세보기 수정
  src/App.vue
  src/pages/map/MapView.vue
Labels: ♻️ refactor, 💟 style, 🍾영오

#50 Feat/#1 fcm 설정 및 의존성 추가
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/api/notification/notification.js
  src/components/notification/NotificationCard.vue
  src/components/notification/NotificationCardHeader.vue
  src/components/notification/NotificationCardMeta.vue
  src/firebase.js
  src/pages/notification/NotificationView.vue
  src/stores/notification/notification.js
  src/utils/fcm.js
Labels: ♻️ refactor, ⭐ feat, ⚽ 경민

#51 feat: /map 상세보기 기능 백엔드 연동
  package.json
  src/App.vue
  src/api/property/property.js
  src/main.js
  src/pages/map/MapView.vue
  src/router/index.js
Labels: ♻️ refactor, ⭐ feat

#53 feat: 본인인증 페이지 및 비밀번호 수정 페이지
  package-lock.json
  src/pages/auth/EnterAddress.vue
  src/pages/auth/FindIdView.vue
  src/pages/auth/FindPasswordView.vue
  src/pages/auth/LoginView.vue
  src/pages/auth/SignupView.vue
  src/pages/auth/VerifyIdentity.vue
  src/router/index.js
Labels: ⭐ feat, 🐳 소정

#58 Feat/#57
  package-lock.json
  src/components/common/Header.vue
  src/pages/notification/NotificationView.vue
  src/stores/notification/notification.js
  src/utils/fcm.js
Labels: ♻️ refactor, ⭐ feat, ⚽ 경민

#60 feat: deal 페이지 구현
  src/api/deal/deal.js
  src/components/common/BackButton.vue
  src/pages/deal/DealBuyerView.vue
  src/pages/deal/DealConsumerDocument.vue
  src/pages/deal/DealNoticeView.vue
  src/pages/deal/DealSellerView.vue
  src/pages/deal/DealWaitingListView.vue
  src/router/index.js
Labels: ⭐ feat, 🐱해인

#61 feat: 리뷰 페이지 개발
  src/api/review/review.js
  src/pages/review/ReviewView.vue
  src/pages/review/ReviewWriteView.vue
  src/router/index.js
  src/stores/review/review.js
Labels: ⭐ feat, 🍾영오

#62 feat: 매물 등록페이지 API 연동 및 메인 페이지 개발
  package-lock.json
  src/api/codef/README.md
  src/api/codef/codef.example.js
  src/api/codef/codef.js
  src/api/property/property.js
  src/assets/Image_fx.jpg
  src/components/common/Button.vue
  src/components/main/MainActionButtons.vue
  src/components/main/MainHeroSection.vue
  src/components/main/MainPropertySection.vue
  src/components/property/PropertyBasicInfoForm.vue
  src/pages/MainView.vue
  src/pages/property/PropertyRegisterView.vue
  src/stores/codef/codef.js
Labels: ⭐ feat, 🐯 현빈

#64 feat: 채팅 다중 구독, 페이지네이션
  src/pages/chat/ChatListView.vue
  src/pages/chat/ChatRoomView.vue
  src/utils/useStomp.js
Labels: ♻️ refactor, 🎸수연

#68 feat: 채팅방 나가기
  src/pages/chat/ChatRoomView.vue
  src/stores/chat/chat.js
Labels: ⭐ feat, 🎸수연

#67 refactor: 리뷰 페이지 이동 수정
  src/pages/map/MapView.vue
Labels: ♻️ refactor, 🍾영오

#74 feat: 본인인증 페이지 및 아이콘 수정
  src/App.vue
  src/pages/auth/LoginView.vue
  src/pages/auth/SignupView.vue
  src/pages/auth/VerifyIdentity.vue
  src/pages/user/MyPageView.vue
  src/pages/user/ProfileEditView.vue
  src/pages/user/WithdrawView.vue
  src/router/index.js
Labels: ⭐ feat, 🐳 소정

#75 chore: 공용 컴포넌트 수정
  src/components/common/Header.vue
  src/components/common/Sidebar.vue
  src/pages/deal/DealWaitingListView.vue
Labels: 🛠️ chore, 🐱해인

#81 feat: 백엔드 연동 및 로그인 여부 확인 구현
  src/api/property/property.js
  src/pages/auth/LoginView.vue
  src/pages/map/MapView.vue
  src/pages/review/ReviewWriteView.vue
  src/router/index.js
Labels: ♻️ refactor, 💟 style, ⭐ feat

#86 feat: 지도, 리뷰, 결제 페이지 반응형 적용
  .mailmap
  src/api/payment/payment.js
  src/composables/useMembership.js
  src/pages/map/MapView.vue
  src/pages/membership/MembershipView.vue
  src/pages/payment/PaymentConfirmView.vue
  src/pages/payment/PaymentView.vue
  src/pages/review/ReviewView.vue
  src/router/index.js
Labels: ♻️ refactor, ⭐ feat, 🍾영오

#83 refactor: 이미지 수정
  src/assets/login_image.png
  src/assets/signup_image.png
  src/pages/auth/LoginView.vue
  src/pages/auth/SignupView.vue
Labels: ♻️ refactor, 🐳 소정

#89 chore: 커밋 내역에서 cursor 제거
  .mailmap
Labels: 🛠️ chore, 🍾영오

#87 style: 매물 등록 페이지 수정
  src/api/real-estate/real-estate.js
  src/components/common/EmptyStateCard.vue
  src/components/common/Header.vue
  src/components/common/Input.vue
  src/components/common/RadioGroup.vue
  src/components/common/Sidebar.vue
  src/components/main/MainPropertySection.vue
  src/components/property/AddressSearch.vue
  src/components/property/AreaInput.vue
  src/components/property/PriceInput.vue
  src/components/property/PropertyBasicInfoForm.vue
  src/components/property/PropertyContactForm.vue
  src/components/property/PropertyDetailForm.vue
  src/components/property/PropertyTypeSelector.vue
  src/pages/property/PropertyRegisterView.vue
  src/utils/formatters.js
Labels: 💟 style, 🐱해인

#90 chore: 커밋 내역에서 cursor 제거
  .mailmap
Labels: 🛠️ chore, 🍾영오

#94 test: 테스트를 위한 로그인 수정
  src/api/axios.js
  src/components/common/Header.vue
  src/pages/auth/LoginView.vue
  src/stores/auth/auth.js
  vite.config.js
Labels: 📝 test, 🐱해인

#95 test: 사이드바 수정 및 거래 목록 불러오기 연동
  src/App.vue
  src/api/auth/auth.js
  src/api/axios.js
  src/api/deal/deal.js
  src/components/common/Header.vue
  src/components/common/SearchModal.vue
  src/components/common/Sidebar.vue
  src/components/common/footer.vue
  src/pages/deal/DealWaitingListView.vue
  src/stores/auth/auth.js
  vite.config.js
Labels: 📝 test, 🔨 fix, 🐱 해인

#97 style: 거래 페이지 수정
  src/components/common/PropertyCardWaiting.vue
  src/pages/deal/DealWaitingListView.vue
Labels: 💟 style, 🐱 해인

#118 refactor: 매물 상세 정보 불러오는 코드 수정
  src/api/deal/deal.js
  src/api/map/map.js
  src/api/publicdata/publicdata.js
  src/api/review/review.js
  src/pages/document/AnalysisReportView.vue
  src/pages/map/MapView.vue
  src/pages/review/ReviewWriteView.vue
  src/router/index.js
  src/stores/map/map.js
Labels: ♻️ refactor, ⭐ feat, 🍾 영오

#121 feat: 알림 연동 완료
  src/api/fcm/fcm.js
  src/api/notification/notification.js
  src/components/notification/NotificationCard.vue
  src/components/notification/NotificationCardMeta.vue
  src/components/notification/NotificationFilter.vue
  src/components/notification/NotificationList.vue
  src/pages/notification/NotificationView.vue
  src/stores/notification/notification.js
  src/utils/fcm.js
Labels: ♻️ refactor, ⭐ feat, ⚽ 경민

#123 refactor: 매물 상세 정보 및 결제 코드 수정
  src/api/codef/codef.js
  src/composables/useMembership.js
  src/pages/map/MapView.vue
  src/pages/payment/PaymentConfirmView.vue
  src/pages/payment/PaymentSuccessView.vue
  src/pages/payment/PaymentView.vue
  src/stores/codef/codef.js
Labels: ♻️ refactor, ⭐ feat, 🍾 영오

#125 feat: 채팅 기능 수정
  TEST_GUIDE.md
  project/zangBu_Back/src/main/resources/assets/Image_fx-iZMVMA4I.jpg
  project/zangBu_Back/src/main/resources/assets/MembershipView-DWovvctl.js
  project/zangBu_Back/src/main/resources/assets/MembershipView-tn0RQdqM.css
  project/zangBu_Back/src/main/resources/assets/fa-brands-400-DFY6gyJh.woff2
  project/zangBu_Back/src/main/resources/assets/fa-regular-400-DdcaUAxu.woff2
  project/zangBu_Back/src/main/resources/assets/fa-solid-900-BQpGBb1f.woff2
  project/zangBu_Back/src/main/resources/assets/fa-v4compatibility-BHaDpj3C.woff2
  project/zangBu_Back/src/main/resources/assets/index-Ci5mVUka.js
  project/zangBu_Back/src/main/resources/assets/index-D_6qN3Je.css
  project/zangBu_Back/src/main/resources/assets/login_image-DFZJ9uFv.png
  project/zangBu_Back/src/main/resources/assets/logo-M_BBjVdl.png
  project/zangBu_Back/src/main/resources/assets/real-estate-DbMcgoMe.js
  project/zangBu_Back/src/main/resources/assets/signup_image-DfsMiRLt.png
  project/zangBu_Back/src/main/resources/favicon.ico
  project/zangBu_Back/src/main/resources/firebase-messaging-sw.js
  project/zangBu_Back/src/main/resources/index.html
  project/zangBu_Back/src/main/webapp/resources/assets/Image_fx-iZMVMA4I.jpg
  project/zangBu_Back/src/main/webapp/resources/assets/MembershipView-DWovvctl.js
  project/zangBu_Back/src/main/webapp/resources/assets/MembershipView-tn0RQdqM.css
  project/zangBu_Back/src/main/webapp/resources/assets/fa-brands-400-DFY6gyJh.woff2
  project/zangBu_Back/src/main/webapp/resources/assets/fa-regular-400-DdcaUAxu.woff2
  project/zangBu_Back/src/main/webapp/resources/assets/fa-solid-900-BQpGBb1f.woff2
  project/zangBu_Back/src/main/webapp/resources/assets/fa-v4compatibility-BHaDpj3C.woff2
  project/zangBu_Back/src/main/webapp/resources/assets/index-Ci5mVUka.js
  project/zangBu_Back/src/main/webapp/resources/assets/index-D_6qN3Je.css
  project/zangBu_Back/src/main/webapp/resources/assets/login_image-DFZJ9uFv.png
  project/zangBu_Back/src/main/webapp/resources/assets/logo-M_BBjVdl.png
  project/zangBu_Back/src/main/webapp/resources/assets/real-estate-DbMcgoMe.js
  project/zangBu_Back/src/main/webapp/resources/assets/signup_image-DfsMiRLt.png
  project/zangBu_Back/src/main/webapp/resources/favicon.ico
  project/zangBu_Back/src/main/webapp/resources/firebase-messaging-sw.js
  project/zangBu_Back/src/main/webapp/resources/index.html
  src/pages/chat/ChatListView.vue
  src/pages/chat/ChatRoomView.vue
  src/pages/chat/ChatTest.vue
  src/pages/chat/rabbitTest.html
  src/pages/deal/DealNoticeView.vue
  src/pages/deal/DealSellerView.vue
  src/pages/map/MapView.vue
  src/router/index.js
  src/stores/chat/chat.js
  src/utils/useStomp.js
  vite.config.js
Labels: ♻️ refactor, 🎸수연

#127 refactor: 주민등록번호 뒷자리 마스킹처리
  src/components/property/PropertyBasicInfoForm.vue
Labels: ♻️ refactor, 🐯 현빈

#131 refactor: 리뷰 작성 수정
  src/api/review/review.js
  src/pages/review/ReviewView.vue
  src/pages/review/ReviewWriteView.vue
  src/stores/review/review.js
Labels: ♻️ refactor, 🍾 영오

#133 feat: 초본 조회 성공 메시지
  src/pages/user/MyPageView.vue
Labels: ⭐ feat, 🐯 현빈

#134 refactor: 주소 검증 수정
  src/api/map/map.js
  src/pages/map/MapView.vue
  src/pages/review/ReviewView.vue
  src/pages/review/ReviewWriteView.vue
Labels: ♻️ refactor, 🍾 영오

#139 style: 단위 변환
  .github/COMMIT_MESSAGE_TEMPLATE.txt
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  src/components/common/PropertyCardWaiting.vue
Labels: 💟 style, 🐱 해인
